---
- name: add lines to a file - version 3
  hosts: localhost 
  tasks: 
    - name: add lines
      blockinfile:
        path: /root/git_repositories/ansible_playbooks/myfile
        create: yes
        block: |
          this is line 1
          this is line 2