---
all: #all servers
  hosts: #ungrouped
  children: 
    group1:
      hosts:
        host1:
          ansible_host: 10.108.0.4
          
    group2: #group name 
      hosts:
        host2:
          ansible_host: 10.108.0.5